### ISSUE TITLE
question about the external potential

### ISSUE THREAD

**Issue by ley61** [masashitsubaki/QuantumDeepField_molecule#1]
Dear authors, I have read your paper "Phys. Rev. Lett. 125, 206401" and enjoy it very much. 

However I have a problem now about the choose of the external potential. In your paper your pick a gaussian potential as the target of HKS net. However, if I remember correctly, the true external potential corresponding to the electron density of a molecule is the coulomb potential of the each atom. 

I just want to know whether it's true to use a coulomb potential instead of gaussian?

**Comment by masashitsubaki** [comment]
I'm sorry for the late reply. Yes, we have chosen the Gaussian-based external potential because we have just followed the recent work of [Bypassing the KS equations with ML](https://www.nature.com/articles/s41467-017-00839-3) and actually obtained the reasonable performance in generating the electron density as shown in Figure 4 in our paper.

As we have discussed in the [Supplemental Material](https://journals.aps.org/prl/supplemental/10.1103/PhysRevLett.125.206401) and described in the [extension section](https://github.com/masashitsubaki/QuantumDeepField_molecule#extension) of the README, you can use other forms (e.g., a Coulomb) of the external potential instead of Gaussian.

I hope that using other external potentials, you will improve the prediction performance and write your research paper :-)

**Comment by ley61** [comment]
Thank your for your reply. I also wonder wether it's necessary to build a HK DNN net to predict the external potential. Because the functional derivative of the Levy lieb functional F[rho] with respect to the density is the external potential. So maybe it's better to build a DNN represent F[rho], predict energy is simply F[rho] + \int \rho v, then your can backward your net to gain the potential, and use it as your second loss. 
Anyway, it's a naive idea.

**Comment by masashitsubaki** [comment]
Your question is very interesting but I'm sorry that it is not a topic to be discussed in this issue page. The GitHub issue is used for the problem about the code and implementation (not about the research itself). Could you tell me your email address? Or please email to me (tsubaki.masashi@aist.go.jp) for discussing this topic directly :-)

I have a comment. We can consider various ML models for DFT and our QDF is just one of them. Of course, we believe that the current QDF is rather a very primitive (and incomplete) and we are now improving the model.
